###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq_cms'
        environment:
            - RABBITMQ_DEFAULT_USER=rabbit
            - RABBITMQ_DEFAULT_PASS=rabbit
            - RABBITMQ_DEFAULT_VHOST=cms
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
          - './phpdocker/rabbitmq/data/:/var/lib/rabbitmq/'
          - './phpdocker/rabbitmq/log/:/var/log/rabbitmq/'
        networks:
            - mynetwork
    cms-webserver:
        container_name: cms_nginx
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './cms:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8101:80'
        networks:
            - mynetwork
    redis:
        container_name: cms_redis
        image: 'redis:alpine'
#        restart: always
        ports:
            - "6379:6379"
        volumes:
            - /path/to/local/d–∞ta:/root/redis
            - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            - REDIS_PASSWORD=student
            - REDIS_PORT=6379
            - REDIS_DATABASES=1
        networks:
            - mynetwork
    redis-gui:
        container_name: cms_redis_gui
        image: 'redislabs/redisinsight:latest'
        ports:
            - '8001:8001'
        networks:
            - mynetwork
    mysql:
        image: 'mariadb:11.0'
        working_dir: /application
        volumes:
            - '.:/application'
        environment:
            - MYSQL_ROOT_PASSWORD=cms
            - MYSQL_DATABASE=cms
            - MYSQL_USER=cms
            - MYSQL_PASSWORD=cms
        ports:
            - '20002:3306'
        networks:
            - mynetwork
    cms-php-fpm:
        container_name: cms_php_fpm
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './cms:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.2/fpm/conf.d/99-overrides.ini'
        networks:
            - mynetwork
networks:
  mynetwork:
    name: mynetwork

